#server config
server:
  port: 6002
  servlet:
    context-path: /Fabric-Node-Manager

# database connection configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fabricmanager?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: "root"
    password: "123456"

schedule:
  ###block info (pulling data from chain)
  pullBlockSleepTime: 200
  isBlockPullFromZero: false
  pullBlockInitCnts: 1000
  pullBlockTaskFixedDelay: 30000
  ###delete info
  isDeleteInfo: true
  transRetainMax: 10000
  blockRetainMax: 10000
  deleteInfoCron: "0 0/1 * * * ?"
  ###transDaily
  statisticsTransDailyCron: "0 0/1 * * * ?"


#constants
constant:
  ###http request
  isUseSecurity: false   # login's authorization
  verificationCodeMaxAge: 300
  authTokenMaxAge: 1800
  ignoreCheckFront: /account/login,/account/pictureCheckCode,/login,/front/new,/front/find,/channel/generate,/channel/start



#log config
logging:
  config: classpath:log4j2.xml
  level.com.webank.fabric.node.manager: info

#front config
front:
  serverAddress: http://%1s:%2d/Fabric-Front/%3s


#mybatis config
mybatis:
  typeAliasesPackage: com.webank.fabric.node.manager
  mapperLocations: classpath:mapper/*.xml
