#server config
server:
  port: 8080
  servlet:
    context-path: /Fabric-Node-Manager

# database connection configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fabricmanager?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: "root"
    password: "123456"

# spring security
security:
  isUseSecurity: true   # login's authorization
  verificationCodeMaxAge: 300
  authTokenMaxAge: 1800

schedule:
  ###block info (pulling data from chain)
  pullBlockSleepTime: 200
  isBlockPullFromZero: false
  pullBlockInitCnts: 1000
  pullBlockTaskFixedDelay: 30000
  ###delete info
  isDeleteInfo: true
  transRetainMax: 10000
  blockRetainMax: 10000
  deleteInfoCron: "0 0/1 * * * ?"
  ###transDaily
  statisticsTransDailyCron: "0 0/1 * * * ?"


#constants
constant:
  ###http request
  contractDeployTimeOut: 30000  #ms


#log config
logging:
  config: classpath:log4j2.xml
  level.com.webank.fabric.node.manager: debug

#front config
front:
  serverAddress: http://%1s:%2d/Fabric-Front/%3s


#mybatis config
mybatis:
  typeAliasesPackage: com.webank.fabric.node.manager
  mapperLocations: classpath:mapper/*.xml


#httpClient
http-client:
  pool:
    #连接池的最大连接数，0代表不限；如果取0，需要考虑连接泄露导致系统崩溃的后果
    maxTotalConnect: 1000
    #每个路由的最大连接数,如果只调用一个地址,可以将其设置为最大连接数
    maxConnectPerRoute: 200
    # 指客户端和服务器建立连接的超时时间,ms , 最大约21秒,因为内部tcp在进行三次握手建立连接时,默认tcp超时时间是20秒
    connectTimeout: 3000
    # 指客户端从服务器读取数据包的间隔超时时间,不是总读取时间,也就是socket timeout,ms
    readTimeout: 5000
    # 从连接池获取连接的timeout,不宜过大,ms
    connectionRequestTimout: 200
    # 重试次数
    retryTimes: 3
    charset: UTF-8
    # 长连接保持时间 单位s,不宜过长
    keepAliveTime: 10
